#!/bin/sh
set -e

PORT="${PORT:-8080}"

# Write shard config from environment variables so models are picked up
# without needing a volume-mounted config file.
mkdir -p /data/.shards
cat > /data/.shards/config <<EOF
# Generated by docker-entrypoint.sh — override via environment variables
LLM_URL     ${LLM_URL:-http://host.docker.internal:11434/v1}
LLM_KEY     ${LLM_KEY:-ollama}
LLM_MODEL   ${LLM_MODEL:-qwen3.5:27b}
EMBED_MODEL ${EMBED_MODEL:-nomic-embed-text}
EOF

echo "[shard] LLM_URL=${LLM_URL:-http://host.docker.internal:11434/v1}"
echo "[shard] LLM_MODEL=${LLM_MODEL:-qwen3.5:27b}"
echo "[shard] EMBED_MODEL=${EMBED_MODEL:-nomic-embed-text}"

echo "[shard] starting daemon..."
shard daemon &
DAEMON_PID=$!

# Wait for daemon IPC socket to be ready
sleep 1

echo "[shard] daemon pid=$DAEMON_PID"
echo "[shard] starting HTTP MCP server on 0.0.0.0:${PORT}..."

# --http-host 0.0.0.0 binds on all interfaces (required inside a container)
# The config default is 127.0.0.1 which would be unreachable from outside
exec shard mcp --http "${PORT}" --http-host 0.0.0.0
